version: '3'

services:
  api:
    container_name: api
    image: api:1.0
    build: '.'
    env_file:
      - '.env'
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
    networks:
      - front-tier
      - back-tier
    command: bash -c "npm run build --prefix client && npm run prod"
    # depends_on:
      # - redis
      # - db

networks:
  front-tier:
  back-tier: