version: '3'

services:
  api:
    container_name: api
    image: api:1.0
    build: '.'
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
      - '/app/client/'
    networks:
      - front-tier
      - back-tier
    command: "npm run local"

  client:
    container_name: client
    image: client:1.0
    build: '.'
    env_file:
      - '.env'
    ports:
      - '3000:3000'
    volumes:
      - './client:/app/client'
    links:
      - api
    depends_on:
      - api
    networks:
      - front-tier
      - back-tier
    command: bash -c "npm rebuild node-sass --prefix client && npm run client"

networks:
  front-tier:
  back-tier: